"""
Synthetic-image traces (Experimental) — spectral statistics of the noise
residual. No trained model and no verdict.

Many generators upsample with (transposed) convolutions, which leaves a
periodic pattern in the high-frequency residual: sharp peaks in its power
spectrum and a periodic autocorrelation. This module measures those peaks:

- Corvi, Cozzolino, Zingarini, Poggi, Nagano, Verdoliva, "On the detection of
  synthetic images generated by diffusion models", ICASSP 2023 (residual
  power spectrum / autocorrelation showing generator-specific peaks).
- Durall, Keuper, Keuper, "Watch your up-convolution: CNN based generative
  deep neural networks are failing to reproduce spectral distributions",
  CVPR 2020 (azimuthally averaged spectrum, high-frequency behaviour).

Residual: prnu.noise_extract (wavelet, db4). Spectrum: Welch average over
128×128 Hann-windowed tiles (stride 64) of a centre crop ≤ 1024 px (never
resized — resampling creates/destroys exactly these peaks). Peak strength =
max over frequencies of (log power − local 9×9 median of log power), in dB,
excluding DC, the two axes and the Nyquist rows/columns (±1 bin of 0.5
cycles/px: Bayer demosaicing puts energy there in every camera image; they
are reported separately as "Nyquist-line peak"). Peaks at multiples of 1/8 cycle/px coincide
with the JPEG 8×8 block grid; for JPEG (or JPEG-gridded) images they are
excluded and reported separately as compression.
"""
import numpy as np
from scipy.ndimage import median_filter

from .prnu import _crop, noise_extract
from .util import (error_result, fig_to_array, image_format, jpeg_grid_offset,
                   load_array, make_result)

TILE, STEP, MAX_SIDE = 128, 64, 1024
# Calibration (16 photos: sampleImg + skimage astronaut/camera/moon/brick/
# grass/gravel/ihc/hubble/retina/coffee/rocket/chelsea/cell + 2 crops, each
# as PNG, JPEG q20/50/75/90/100 and 0.5× downscale; 107 negatives):
# off-grid peak max 8.5 dB, p99 8.0, p95 6.3 → 0/107 above 9 dB.
# Injected patterns (share of 16 above 9 dB): period-3 ±1.5 grey PNG 16/16;
# period-3 ±3 JPEG q90 12/16, q75 0/16. 2×2 checkerboards sit on the
# Nyquist lines, now excluded (reported as "Nyquist-line peak").
# Hold-out with Nyquist lines excluded (Bayer+noise+bilinear demosaic, half
# sharpened, PNG/JPEG q75/85/92, other scenes/seeds + reviewer's 30
# demosaiced files): 1/110 above 9 dB (max 10.7); period-3 ±1.5 found
# 20/20 PNG, 20/20 JPEG q92.
PEAK_NOTICE_DB = 9.0
GRID_STRENGTH = 1.15  # util.jpeg_grid_offset strength above which a PNG is
#                       treated as having a JPEG past (grid peaks excluded)

LIMITATIONS = [
    "Cannot reliably identify AI-generated images. There is no trained "
    "detector here, only a spectral measurement.",
    "Modern diffusion models, resizing, cropping plus rescaling, and JPEG "
    "compression remove or mask these traces: absence of peaks says nothing "
    "about how the image was made.",
    "Periodic residual peaks also come from ordinary processing: resampling, "
    "demosaicing, sharpening, screen/print re-capture, halftoning, and "
    "periodic scene texture (fabric, brick, grids).",
    "Peaks on the Nyquist rows/columns (period-2 patterns, e.g. a 2× "
    "upsampling checkerboard) are not evaluated: demosaicing puts energy "
    "there in ordinary camera images.",
    "Peaks at multiples of 1/8 cycle/px on JPEG images cannot be separated "
    "from compression and are not evaluated as generation traces.",
]


def _welch(x):
    """Mean |FFT|² over Hann-windowed tiles (unshifted, DC at [0, 0])."""
    win = np.outer(np.hanning(TILE), np.hanning(TILE))
    acc, n = np.zeros((TILE, TILE)), 0
    for y in range(0, x.shape[0] - TILE + 1, STEP):
        for xx in range(0, x.shape[1] - TILE + 1, STEP):
            t = x[y:y + TILE, xx:xx + TILE]
            acc += np.abs(np.fft.fft2((t - t.mean()) * win)) ** 2
            n += 1
    return acc / n, n


def _radial(p):
    """Azimuthal average of 10·log10(p) vs normalised frequency (1 = Nyquist)."""
    f = np.fft.fftfreq(TILE)
    r = np.hypot(*np.meshgrid(f, f, indexing="ij")) / 0.5
    bins = np.minimum((r * (TILE // 2)).astype(int), TILE // 2)
    lp = 10 * np.log10(p + 1e-12)
    prof = np.bincount(bins.ravel(), lp.ravel()) / np.bincount(bins.ravel())
    return np.arange(prof.size) / (TILE // 2), prof


def measure(img, is_jpeg):
    """Residual-spectrum peak statistics of a 2-D grey array (module doc)."""
    res = noise_extract(img)
    grid_strength = float(jpeg_grid_offset(img)[2])
    exclude_grid = bool(is_jpeg or grid_strength > GRID_STRENGTH)
    p, n = _welch(res)
    lp = 10 * np.log10(p + 1e-12)
    excess = lp - median_filter(lp, size=9, mode="wrap")
    k = np.arange(TILE)
    near = lambda m: (np.minimum(k % m, (-k) % m) <= 1)  # noqa: E731
    axis = near(TILE)  # within 1 bin of zero frequency
    nyq = np.abs(k - TILE // 2) <= 1  # within 1 bin of Nyquist (±0.5 cycles/px)
    nyq_lines = nyq[:, None] | nyq[None, :]
    allowed = ~(axis[:, None] | axis[None, :]) & ~nyq_lines
    grid = near(TILE // 8)[:, None] & near(TILE // 8)[None, :] & ~(axis[:, None] & axis[None, :])
    if exclude_grid:
        allowed &= ~grid
    masked = np.where(allowed, excess, -np.inf)
    r, c = np.unravel_index(np.argmax(masked), masked.shape)
    fy, fx = np.fft.fftfreq(TILE)[[r, c]]
    return dict(res_std=float(res.std()), p=p, excess=excess, allowed=allowed,
                rc=(int(r), int(c)), peak_db=float(masked[r, c]),
                freq=(float(fy), float(fx)), grid_db=float(excess[grid].max()),
                nyquist_db=float(excess[nyq_lines & ~(axis[:, None] & axis[None, :])].max()),
                exclude_grid=exclude_grid, grid_strength=grid_strength, tiles=n)


def _plots(p, excess, allowed, peak_rc, radial):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    ext = [-0.5, 0.5, 0.5, -0.5]
    fig, ax = plt.subplots(figsize=(4.5, 4))
    im = ax.imshow(np.fft.fftshift(np.where(allowed, excess, 0)), cmap="magma",
                   extent=ext, vmin=0, vmax=max(PEAK_NOTICE_DB * 1.5, 1))
    fy, fx = np.fft.fftfreq(TILE)[list(peak_rc)]
    ax.plot(fx, fy, "c+", ms=14)
    ax.set_xlabel("horizontal frequency (cycles/px)")
    ax.set_ylabel("vertical frequency (cycles/px)")
    fig.colorbar(im, ax=ax, label="dB above local median")
    spec = fig_to_array(fig)

    ac = np.real(np.fft.ifft2(p))
    ac = np.fft.fftshift(ac / ac[0, 0])
    c = TILE // 2
    ac = ac[c - 16:c + 17, c - 16:c + 17].copy()
    ac[16, 16] = 0  # zero lag = 1 by definition; hide it so structure shows
    fig, ax = plt.subplots(figsize=(4.5, 4))
    lim = max(np.abs(ac).max(), 1e-6)
    im = ax.imshow(ac, cmap="coolwarm", vmin=-lim, vmax=lim, extent=[-16.5, 16.5, 16.5, -16.5])
    ax.set_xlabel("horizontal lag (px)")
    ax.set_ylabel("vertical lag (px)")
    fig.colorbar(im, ax=ax, label="normalised autocorrelation")
    acorr = fig_to_array(fig)

    fig, ax = plt.subplots(figsize=(5, 3))
    ax.plot(*radial)
    ax.set_xlabel("spatial frequency (1 = Nyquist)")
    ax.set_ylabel("mean log power (dB)")
    ax.grid(alpha=0.3)
    az = fig_to_array(fig)
    return spec, acorr, az


def analyze_synthetic_traces(image_path):
    try:
        gray, _ = load_array(image_path, "L")
        img, (y0, x0) = _crop(gray, MAX_SIDE)
        h, w = img.shape
        if min(h, w) < 2 * TILE:
            return make_result("insufficient_data",
                               f"Image {w}×{h} px is too small for a spectral estimate "
                               f"(needs ≥ {2 * TILE} px per side).", limitations=LIMITATIONS)
        is_jpeg = image_format(image_path) == "JPEG"
        m = measure(img, is_jpeg)
        if m["res_std"] < 0.05:
            return make_result("insufficient_data",
                               "The image has essentially no high-frequency residual "
                               "(flat content); nothing to measure.", limitations=LIMITATIONS)
        peak_db, grid_db, exclude_grid = m["peak_db"], m["grid_db"], m["exclude_grid"]
        fy, fx = m["freq"]
        period = 1 / np.hypot(fy, fx)
        f_img, _ = _welch(img)
        rad = _radial(f_img)
        hf = rad[1][(rad[0] >= 0.9) & (rad[0] <= 1.0)].mean()
        mid = rad[1][(rad[0] >= 0.4) & (rad[0] <= 0.5)].mean()

        metrics = {
            "Off-grid residual peak (dB above local median)": round(peak_db, 2),
            "Peak frequency (cycles/px, vertical, horizontal)": f"{fy:+.3f}, {fx:+.3f}",
            "Peak period (px)": round(float(period), 2),
            "8-px-grid peak (dB)": round(grid_db, 2),
            "Nyquist-line peak (dB, demosaicing/CFA)": round(m["nyquist_db"], 2),
            "Azimuthal power 0.9–1.0 vs 0.4–0.5 Nyquist (dB)": round(float(hf - mid), 2),
            "Tiles averaged": m["tiles"],
            "Analysed region (px)": f"{w}×{h} at x={x0}, y={y0}",
        }
        findings = []
        if peak_db > PEAK_NOTICE_DB:
            findings.append(("notice",
                             f"Periodic peak {peak_db:.1f} dB above the local spectral "
                             f"background at ({fy:+.3f}, {fx:+.3f}) cycles/px (period ≈ "
                             f"{period:.1f} px). Generator upsampling leaves such peaks, "
                             "but so do resampling, demosaicing, sharpening, re-capture "
                             "and periodic textures."))
        else:
            findings.append(("info",
                             f"Largest off-grid residual peak {peak_db:.1f} dB (notice level "
                             f"{PEAK_NOTICE_DB:.0f} dB): no periodic residual pattern at this "
                             "sensitivity. This says nothing about whether the image is "
                             "AI-generated."))
        if m["nyquist_db"] > PEAK_NOTICE_DB:
            findings.append(("info",
                             f"Peak {m['nyquist_db']:.1f} dB on the Nyquist rows/columns "
                             "(±0.5 cycles/px) not evaluated: camera demosaicing (Bayer "
                             "CFA interpolation) puts energy there, as do 2× upsampling "
                             "and checkerboard artefacts — these cannot be told apart."))
        if exclude_grid:
            findings.append(("info",
                             f"8-px-grid peaks ({grid_db:.1f} dB) excluded: "
                             + ("the file is JPEG" if is_jpeg else "a JPEG block grid is visible")
                             + "; peaks at k/8 cycles/px are attributed to compression."))
        images = dict(zip(("Residual power spectrum (excess over local median)",
                           "Residual autocorrelation (±16 px)",
                           "Azimuthally averaged image spectrum"),
                          _plots(m["p"], m["excess"], m["allowed"], m["rc"], rad)))
        details = {"peak_db": peak_db, "peak_freq": [fy, fx],
                   "grid_peak_db": grid_db, "nyquist_peak_db": m["nyquist_db"], "grid_excluded": bool(exclude_grid),
                   "jpeg_grid_strength": m["grid_strength"], "tiles": m["tiles"],
                   "radial_freq": rad[0].tolist(), "radial_db": rad[1].tolist()}
        return make_result("ok", "Measured periodic peaks in the noise-residual power "
                           "spectrum (experimental; no AI-image classifier).",
                           findings, metrics, images, limitations=LIMITATIONS, details=details)
    except Exception as e:  # noqa: BLE001
        return error_result(e, LIMITATIONS)
